// rebuild/resources/js/Pages/Guest/Track.vue
<script setup>
import {Head,Link} from '@inertiajs/vue3';
import {computed,onMounted,onUnmounted,ref} from 'vue';
import CustomerShell from '../../Components/CustomerShell.vue';

const props=defineProps({transactions:Array});
const query=ref('');
const loading=ref(false);
const error=ref('');
const mode=ref('');
const orders=ref([]);
const detail=ref(null);
const feed=ref([...(props.transactions||[])]);
const copied=ref(false);
let detailTimer=null,feedTimer=null;
const detailRefreshing=ref(false);
let disposed=false;
let selectionVersion=0;

const money=v=>'Rp '+Number(v||0).toLocaleString('id-ID');
const statusMeta=s=>({
 pending:['Menunggu Pembayaran','Selesaikan pembayaran sebelum waktu habis.','amber'],
 paid:['Pembayaran Diterima','Pembayaran sudah terverifikasi.','blue'],
 processing:['Sedang Diproses','Pesanan sedang diproses sistem.','blue'],
 success:['Berhasil','Pesanan selesai diproses.','green'],
 failed:['Gagal','Pesanan tidak berhasil diproses.','red'],
 cancelled:['Dibatalkan','Transaksi dibatalkan dan tidak akan diproses.','red'],
 expired:['Kedaluwarsa','Waktu pembayaran telah berakhir.','gray'],
 refunded:['Refund','Pengembalian dana sedang atau telah diproses.','amber'],
}[s]||['Diproses','Status sedang diperbarui.','blue']);
const sourceLabel=s=>({payment:'Pembayaran',processing:'Proses Pesanan',delivery:'Pengiriman',admin:'Admin',system:'Sistem'}[s]||'Sistem');
const date=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'-';
const terminal=computed(()=>detail.value&&['success','failed','cancelled','expired','refunded'].includes(detail.value.fulfillmentStatus));

async function json(url,options={}){
 const token=document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
 const response=await fetch(url,{cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':token,...(options.headers||{})},...options});
 const data=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})?.[0]?.[0]||'Permintaan gagal.');
 return data;
}
async function search(){
 if(loading.value)return;
 const value=query.value.trim();
 stopDetailPolling();selectionVersion++;detail.value=null;orders.value=[];mode.value='';copied.value=false;
 if(!value){error.value='Masukkan nomor invoice atau nomor WhatsApp.';return;}
 loading.value=true;error.value='';
 const version=selectionVersion;
 try{
  const data=await json('/orders/track/search',{method:'POST',body:JSON.stringify({query:value})});
  if(disposed||version!==selectionVersion)return;
  mode.value=data.mode;
  if(data.mode==='order'){detail.value=data.order;startDetailPolling();}
  else{orders.value=data.orders||[];}
 }catch(e){if(!disposed&&version===selectionVersion)error.value=e.message||'Pesanan tidak ditemukan.'}
 finally{if(!disposed&&version===selectionVersion)loading.value=false;}
}
async function openOrder(trackingToken){
 if(loading.value)return;
 stopDetailPolling();selectionVersion++;detail.value=null;copied.value=false;
 const version=selectionVersion;
 loading.value=true;error.value='';
 try{
  const data=await json('/orders/track/status',{method:'POST',body:JSON.stringify({tracking_token:trackingToken})});
  if(disposed||version!==selectionVersion)return;
  detail.value=data.order;orders.value=[];mode.value='order';startDetailPolling();
 }catch(e){if(!disposed&&version===selectionVersion)error.value=e.message||'Pesanan tidak ditemukan.'}
 finally{if(!disposed&&version===selectionVersion)loading.value=false;}
}
async function refreshDetail(){
 if(!detail.value?.trackingToken||detailRefreshing.value||disposed)return;
 const token=detail.value.trackingToken;
 const version=selectionVersion;
 detailRefreshing.value=true;
 try{
  const data=await json('/orders/track/status',{method:'POST',body:JSON.stringify({tracking_token:token})});
  if(disposed||version!==selectionVersion||detail.value?.trackingToken!==token)return;
  detail.value=data.order;if(terminal.value)stopDetailPolling();
 }catch{}finally{detailRefreshing.value=false;}
}
async function refreshFeed(){
 try{const data=await json('/orders/track/feed');feed.value=data.transactions||feed.value;}catch{}
}
function startDetailPolling(){stopDetailPolling();if(!terminal.value)detailTimer=setInterval(refreshDetail,3000);}
function stopDetailPolling(){if(detailTimer){clearInterval(detailTimer);detailTimer=null;}}
async function copyInvoice(){if(!detail.value?.referenceId||detail.value?.referenceMasked)return;await navigator.clipboard?.writeText(detail.value.referenceId);copied.value=true;setTimeout(()=>copied.value=false,1400);}
onMounted(()=>{feedTimer=setInterval(refreshFeed,15000);});
onUnmounted(()=>{disposed=true;selectionVersion++;stopDetailPolling();if(feedTimer)clearInterval(feedTimer);});
</script>

<template>
<Head title="Cek Pesanan"/>
<CustomerShell>
<main class="lf-track-page">
 <section class="lf-container lf-track-hero">
  <div>
   <p class="lf-eyebrow">PELACAKAN TRANSAKSI</p>
   <h1>Cek status pesananmu</h1>
   <p>Masukkan nomor invoice atau nomor WhatsApp yang dipakai saat checkout. Status diperbarui otomatis dari server.</p>
  </div>
  <div class="lf-track-search">
   <svg viewBox="0 0 24 24"><path d="m21 21-4.3-4.3m1.3-5.7a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"/></svg>
   <input v-model="query" @keyup.enter="search" aria-label="Nomor invoice atau nomor WhatsApp" placeholder="Masukkan nomor invoice atau nomor WhatsApp">
   <button :disabled="loading" @click="search">{{loading?'Mencari...':'Periksa'}}</button>
  </div>
  <p v-if="error" role="alert" class="lf-track-error">{{error}}</p>
 </section>

 <p v-if="mode==='phone' && !orders.length && !loading && !error" class="lf-container lf-empty" role="status">Tidak ada pesanan untuk nomor WhatsApp ini. Periksa kembali nomor yang digunakan saat checkout.</p>

 <section v-if="orders.length" class="lf-container lf-track-results">
  <div class="lf-track-section-head"><div><p class="lf-eyebrow">RIWAYAT NOMOR</p><h2>Pesanan ditemukan</h2></div><span>{{orders.length}} transaksi</span></div>
  <div class="lf-track-order-list">
   <button v-for="item in orders" :key="item.trackingToken" :disabled="loading" @click="openOrder(item.trackingToken)">
    <div><strong>{{item.maskedReferenceId}}</strong><small>{{item.productName}} · {{item.packageLabel}}</small></div>
    <div><b>{{money(item.total)}}</b><span :class="'status-'+item.status">{{statusMeta(item.status)[0]}}</span></div>
   </button>
  </div>
 </section>

 <section v-if="detail" class="lf-container lf-track-detail">
  <div class="lf-track-detail-head">
   <div><p class="lf-eyebrow">DETAIL TRANSAKSI</p><h2>{{detail.productName}}</h2><p>{{detail.packageLabel}}</p></div>
   <span class="lf-live-badge" :class="{done:terminal}"><i></i>{{terminal?'STATUS FINAL':'LIVE'}}</span>
  </div>

  <div class="lf-track-grid">
   <div class="lf-track-summary">
    <div class="lf-track-invoice">
     <div><small>Nomor Invoice</small><strong>{{detail.referenceId}}</strong></div>
     <button v-if="!detail.referenceMasked" @click="copyInvoice">{{copied?'Tersalin':'Salin'}}</button><span v-else class="text-[8px] font-bold uppercase tracking-[0.08em] text-white/35">Terlindungi</span>
    </div>
    <div class="lf-track-status-card" :class="'tone-'+statusMeta(detail.fulfillmentStatus)[2]">
     <span></span><div><small>Status Pesanan</small><strong>{{statusMeta(detail.fulfillmentStatus)[0]}}</strong><p>{{statusMeta(detail.fulfillmentStatus)[1]}}</p></div>
    </div>
    <dl class="lf-track-meta">
     <div><dt>Produk</dt><dd>{{detail.productName}}</dd></div>
     <div><dt>Nominal</dt><dd>{{detail.packageLabel}}</dd></div>
     <div><dt>Tujuan</dt><dd>{{detail.destination||'Disembunyikan'}}</dd></div>
     <div><dt>Metode Pembayaran</dt><dd>{{detail.paymentMethod}}</dd></div>
     <div><dt>Status Pembayaran</dt><dd>{{statusMeta(detail.paymentStatus)[0]}}</dd></div>
     <div><dt>Total</dt><dd class="money">{{money(detail.total)}}</dd></div>
     <div><dt>Dibuat</dt><dd>{{date(detail.createdAt)}}</dd></div>
     <div><dt>Update</dt><dd>{{date(detail.updatedAt)}}</dd></div>
    </dl>
    <div class="lf-track-sensitive">
     <strong>Butuh kode/hasil pesanan?</strong>
     <p>Data sensitif hanya ditampilkan melalui halaman akses guest yang memakai kode akses, atau dari Riwayat Pesanan jika kamu login.</p>
     <Link href="/login" class="lf-secondary">Masuk Akun</Link>
    </div>
   </div>

   <aside class="lf-track-timeline">
    <header><div><h3>Log Realtime</h3><p>Sinkron setiap 3 detik</p></div><button :disabled="detailRefreshing" aria-label="Perbarui status pesanan" @click="refreshDetail">↻</button></header>
    <ol>
     <li v-for="event in detail.events" :key="event.id">
      <i></i><div><small>{{sourceLabel(event.source)}}</small><strong>{{event.label}}</strong><time>{{date(event.createdAt)}}</time></div>
     </li>
     <li v-if="!detail.events?.length"><i></i><div><small>Sistem</small><strong>Pesanan tercatat</strong><time>Menunggu pembaruan berikutnya</time></div></li>
    </ol>
   </aside>
  </div>
 </section>

 <section class="lf-track-feed">
  <div class="lf-container">
   <div class="lf-track-section-head"><div><p class="lf-eyebrow">TRANSAKSI TERBARU</p><h2>Aktivitas LFAMILIA</h2><p>Invoice dimasking untuk menjaga privasi pelanggan.</p></div><span class="lf-live-badge"><i></i>LIVE</span></div>
   <div class="lf-feed-table">
    <div class="lf-feed-row lf-feed-head"><span>Invoice</span><span>Produk</span><span>Total</span><span>Status</span><span>Waktu</span></div>
    <div v-for="item in feed" :key="item.maskedReferenceId+item.createdAt" class="lf-feed-row">
     <strong>{{item.maskedReferenceId}}</strong><span>{{item.productName}}<small>{{item.packageLabel}}</small></span><b>{{money(item.total)}}</b><em :class="'status-'+item.status">{{statusMeta(item.status)[0]}}</em><time>{{date(item.createdAt)}}</time>
    </div>
    <div v-if="!feed.length" class="lf-empty">Belum ada transaksi untuk ditampilkan.</div>
   </div>
  </div>
 </section>
</main>
</CustomerShell>
</template>

// app/track/page.tsx
"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  Clock3,
  Copy,
  History,
  Loader2,
  PackageCheck,
  Radio,
  Search,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { StoreLayout } from "@/components/store-layout";
import { formatRupiah } from "@/lib/store-data";

type OrderEvent = { source: string; status: string; createdAt: string };
type TrackedOrder = {
  referenceId: string;
  productName: string;
  packageLabel: string;
  destination: string | null;
  total: number;
  paymentMethod: string;
  paymentChannel: string;
  paymentStatus: string;
  fulfillmentStatus: string;
  fulfillmentType: "automatic" | "manual";
  voucherCode?: string | null;
  events: OrderEvent[];
  createdAt: string;
  updatedAt: string;
};
type OrderSummary = {
  referenceId: string | null;
  maskedReferenceId: string;
  productName: string;
  packageLabel: string;
  total: number;
  status: string;
  createdAt: string;
};

const paymentLabels: Record<string, string> = {
  pending: "Menunggu pembayaran",
  paid: "Pembayaran diterima",
  expired: "Pembayaran kedaluwarsa",
  failed: "Pembayaran gagal",
};
const fulfillmentLabels: Record<string, string> = {
  waiting_payment: "Menunggu pembayaran",
  processing: "Sedang diproses sistem",
  pending: "Sedang diproses sistem",
  manual_pending: "Menunggu diproses admin",
  needs_review: "Perlu diperiksa admin",
  success: "Pesanan selesai",
  error: "Pengiriman gagal",
  failed: "Pengiriman gagal",
};
const eventLabels: Record<string, string> = {
  created: "Pesanan dibuat",
  pending: "Menunggu pembayaran",
  paid: "Pembayaran diterima",
  settlement: "Pembayaran diterima",
  processing: "Pesanan sedang diproses",
  manual_pending: "Menunggu diproses admin",
  success: "Pesanan berhasil",
  failed: "Transaksi gagal",
  failure: "Transaksi gagal",
  expired: "Pembayaran kedaluwarsa",
  expire: "Pembayaran kedaluwarsa",
  cancel: "Transaksi dibatalkan",
  needs_review: "Perlu diperiksa admin",
  error: "Terjadi kendala pemrosesan",
};
const sourceLabels: Record<string, string> = {
  payment: "Pembayaran",
  system: "LFAMILIA",
  balance: "Saldo",
  processing: "Pemrosesan",
  delivery: "Pengiriman",
  admin: "Admin",
};
const publicStatusLabels: Record<string, string> = {
  pending: "Menunggu pembayaran",
  paid: "Pembayaran diterima",
  processing: "Diproses",
  manual_pending: "Menunggu admin",
  needs_review: "Perlu diperiksa",
  success: "Berhasil",
  failed: "Gagal",
  error: "Gagal",
  expired: "Kedaluwarsa",
};

function dateLabel(value: string) {
  const date = new Date(value.includes("T") ? value : `${value.replace(" ", "T")}Z`);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("id-ID", {
    dateStyle: "medium",
    timeStyle: "medium",
    timeZone: "Asia/Jakarta",
  }).format(date) + " WIB";
}
function statusPresentation(order: TrackedOrder) {
  if (["failed", "expired"].includes(order.paymentStatus))
    return { label: paymentLabels[order.paymentStatus], tone: "text-red-300 bg-red-400/10", Icon: XCircle };
  if (["error", "failed", "needs_review"].includes(order.fulfillmentStatus))
    return { label: fulfillmentLabels[order.fulfillmentStatus], tone: "text-amber-300 bg-amber-400/10", Icon: AlertTriangle };
  if (order.fulfillmentStatus === "success")
    return { label: "Berhasil", tone: "text-[#cfff72] bg-[#b9ff35]/10", Icon: CheckCircle2 };
  return {
    label: order.paymentStatus === "paid"
      ? fulfillmentLabels[order.fulfillmentStatus] || "Sedang diproses"
      : paymentLabels[order.paymentStatus] || "Menunggu pembayaran",
    tone: "text-sky-300 bg-sky-400/10",
    Icon: Clock3,
  };
}
function isFinal(order: TrackedOrder) {
  return ["failed", "expired"].includes(order.paymentStatus)
    || ["success", "failed", "error"].includes(order.fulfillmentStatus);
}
function looksLikeInvoice(value: string) {
  return value.trim().toUpperCase().startsWith("LF");
}

export default function TrackPage() {
  const [query, setQuery] = useState("");
  const [activeReference, setActiveReference] = useState("");
  const [order, setOrder] = useState<TrackedOrder | null>(null);
  const [phoneOrders, setPhoneOrders] = useState<OrderSummary[]>([]);
  const [transactions, setTransactions] = useState<OrderSummary[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);

  const loadPublicFeed = useCallback(async () => {
    try {
      const response = await fetch("/api/orders/search", { cache: "no-store" });
      const result = await response.json() as { transactions?: OrderSummary[] };
      if (response.ok && Array.isArray(result.transactions)) setTransactions(result.transactions);
    } catch {
      // Feed publik tidak boleh mengganggu fungsi pencarian utama.
    }
  }, []);

  const loadOrder = useCallback(async (referenceId: string, quiet = false) => {
    const clean = referenceId.trim().toUpperCase();
    if (!clean) return;
    if (!quiet) setLoading(true);
    try {
      const response = await fetch("/api/orders/status", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ referenceId: clean }),
        cache: "no-store",
      });
      const result = await response.json() as { order?: TrackedOrder; error?: string };
      if (!response.ok || !result.order) throw new Error(result.error || "Invoice tidak ditemukan.");
      setOrder(result.order);
      setQuery(result.order.referenceId);
      setActiveReference(result.order.referenceId);
      setPhoneOrders([]);
      setError("");
    } catch (reason) {
      if (!quiet) {
        setOrder(null);
        setError(reason instanceof Error ? reason.message : "Status pesanan gagal dimuat.");
      }
    } finally {
      if (!quiet) setLoading(false);
    }
  }, []);

  const searchByPhone = useCallback(async (phone: string) => {
    setLoading(true);
    try {
      const response = await fetch("/api/orders/search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ phone }),
        cache: "no-store",
      });
      const result = await response.json() as { orders?: OrderSummary[]; error?: string };
      if (!response.ok) throw new Error(result.error || "Pesanan tidak ditemukan.");
      const orders = result.orders ?? [];
      setOrder(null);
      setActiveReference("");
      setPhoneOrders(orders);
      setError(orders.length ? "" : "Belum ada pesanan untuk nomor WhatsApp tersebut.");
    } catch (reason) {
      setOrder(null);
      setPhoneOrders([]);
      setError(reason instanceof Error ? reason.message : "Pesanan tidak ditemukan.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const initial = window.setTimeout(() => void loadPublicFeed(), 0);
    const timer = window.setInterval(() => void loadPublicFeed(), 15_000);
    return () => {
      window.clearTimeout(initial);
      window.clearInterval(timer);
    };
  }, [loadPublicFeed]);

  useEffect(() => {
    const value = new URLSearchParams(window.location.search).get("invoice")?.trim().toUpperCase();
    if (!value) return;
    const timer = window.setTimeout(() => {
      setQuery(value);
      setActiveReference(value);
      void loadOrder(value);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [loadOrder]);

  useEffect(() => {
    if (!order || !activeReference || isFinal(order)) return;
    const timer = window.setInterval(() => void loadOrder(activeReference, true), 3000);
    return () => window.clearInterval(timer);
  }, [activeReference, loadOrder, order]);

  async function search(event: FormEvent) {
    event.preventDefault();
    setCopiedCode(false);
    const value = query.trim();
    if (!value) {
      setError("Masukkan nomor invoice atau nomor WhatsApp terlebih dahulu.");
      return;
    }
    if (looksLikeInvoice(value)) await loadOrder(value);
    else await searchByPhone(value);
  }
  function copyId() {
    if (!order) return;
    void navigator.clipboard?.writeText(order.referenceId);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  }
  function copyVoucherCode() {
    if (!order?.voucherCode) return;
    void navigator.clipboard?.writeText(order.voucherCode);
    setCopiedCode(true);
    window.setTimeout(() => setCopiedCode(false), 1500);
  }
  const status = order ? statusPresentation(order) : null;

  return (
    <StoreLayout>
      <main className="mx-auto min-h-[70vh] max-w-4xl px-4 py-10 sm:px-6 sm:py-16">
        <div className="text-center">
          <p className="eyebrow">Lacak pesanan</p>
          <h1 className="section-title">Cek status transaksi</h1>
          <p className="mx-auto mt-3 max-w-xl text-xs leading-5 text-white/42">
            Masukkan invoice LFAMILIA atau nomor WhatsApp yang digunakan saat checkout.
          </p>
        </div>

        <form onSubmit={search} className="panel mt-7 p-4 sm:p-5">
          <label className="field-label" htmlFor="order-query">Invoice / Nomor WhatsApp</label>
          <div className="flex flex-col gap-3 sm:flex-row">
            <Input
              id="order-query"
              value={query}
              onChange={(event) => { setQuery(event.target.value.replace(/\s/g, "")); setError(""); }}
              placeholder="Contoh: LF260903ABC123 atau 081234567890"
              autoComplete="off"
              inputMode="text"
              className="h-11 rounded-lg border-white/10 bg-white/[0.035] font-mono text-sm text-white placeholder:font-sans placeholder:text-white/22"
            />
            <Button type="submit" disabled={loading} className="h-11 rounded-lg bg-[#b9ff35] px-6 font-black text-[#091006] hover:bg-[#d0ff75] disabled:opacity-60">
              {loading ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Search className="mr-2 size-4" />}
              {loading ? "Mencari" : "Cari"}
            </Button>
          </div>
          <p className="mt-2 text-[9px] text-white/28">
            Nomor WhatsApp boleh menggunakan format 08, 628, atau +628. Invoice lama dengan tanda “-” tetap dapat digunakan.
          </p>
        </form>

        {error && <div role="alert" className="panel mt-4 p-6 text-center">
          <Search className="mx-auto size-7 text-white/18" />
          <h2 className="mt-3 font-bold">Pesanan tidak ditemukan</h2>
          <p className="mt-1 text-xs leading-5 text-white/38">{error}</p>
        </div>}

        {phoneOrders.length > 0 && <section className="panel mt-4 overflow-hidden">
          <div className="border-b border-white/[0.08] px-4 py-3 sm:px-5">
            <h2 className="text-sm font-black">Pesanan dari nomor WhatsApp ini</h2>
            <p className="mt-0.5 text-[9px] text-white/35">Nomor WhatsApp hanya menampilkan ringkasan. Gunakan invoice asli untuk membuka detail transaksi.</p>
          </div>
          <div className="divide-y divide-white/[0.06]">
            {phoneOrders.map((item, index) => <div key={`${item.createdAt}-${item.productName}-${index}`} className="flex items-center justify-between gap-3 px-4 py-3 sm:px-5">
              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono text-[10px] font-bold text-[#cfff72]">{item.maskedReferenceId}</span>
                  <span className="rounded-md bg-white/[0.05] px-2 py-1 text-[8px] font-bold text-white/55">{publicStatusLabels[item.status] || item.status}</span>
                </div>
                <p className="mt-1 truncate text-xs font-bold text-white/75">{item.productName} • {item.packageLabel}</p>
                <p className="mt-1 text-[9px] text-white/35">{formatRupiah(item.total)} • {dateLabel(item.createdAt)}</p>
              </div>
              <span className="shrink-0 rounded-lg border border-white/10 bg-white/[0.025] px-3 py-2 text-[9px] font-bold text-white/35">
                Invoice diperlukan
              </span>
            </div>)}
          </div>
        </section>}

        {order && status && <>
          <section className="panel mt-4 overflow-hidden">
            <div className="flex items-start justify-between gap-4 border-b border-white/[0.08] bg-[#b9ff35]/[0.06] p-4 sm:p-5">
              <div>
                <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${status.tone}`}><status.Icon className="size-3" /> {status.label}</span>
                <h2 className="mt-3 text-lg font-black">{fulfillmentLabels[order.fulfillmentStatus] || status.label}</h2>
                <p className="mt-1 text-[10px] text-white/38">Dibuat {dateLabel(order.createdAt)}</p>
              </div>
              <PackageCheck className="size-8 text-[#b9ff35]" />
            </div>
            <div className="p-4 sm:p-5">
              <div className="flex items-center justify-between gap-3 rounded-lg bg-white/[0.035] p-3">
                <span className="break-all font-mono text-xs font-bold text-white/70">{order.referenceId}</span>
                <button type="button" onClick={copyId} className="inline-flex shrink-0 items-center gap-1 text-[10px] font-bold text-[#cfff72]"><Copy className="size-3" />{copied ? "Tersalin" : "Salin Invoice"}</button>
              </div>
              <dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2">
                {[["Produk", order.productName], ["Item", order.packageLabel], ...(order.destination ? [["Tujuan", order.destination]] : []), ["Total", formatRupiah(order.total)]].map(([label, value]) => <div key={label} className="border-b border-white/[0.07] pb-3"><dt className="text-white/32">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>)}
              </dl>

              {order.voucherCode && <div className="mt-4 rounded-lg border border-[#b9ff35]/25 bg-[#b9ff35]/[0.07] p-3">
                <div className="flex items-center justify-between gap-3"><div><span className="text-[9px] font-black uppercase tracking-[0.14em] text-[#cfff72]">Kode Voucher</span><p className="mt-1 text-[9px] text-white/38">Simpan kode ini dan jangan bagikan.</p></div><CheckCircle2 className="size-5 text-[#b9ff35]" /></div>
                <div className="mt-3 flex items-center justify-between gap-3 rounded-lg bg-black/20 p-3"><strong className="break-all font-mono text-sm text-[#d8ff8d]">{order.voucherCode}</strong><button type="button" onClick={copyVoucherCode} className="inline-flex shrink-0 items-center gap-1 text-[10px] font-bold text-[#cfff72]"><Copy className="size-3.5" />{copiedCode ? "Tersalin" : "Salin kode"}</button></div>
              </div>}
            </div>
          </section>

          <section className="panel mt-4 overflow-hidden">
            <div className="flex items-center justify-between gap-3 border-b border-white/[0.08] px-4 py-3 sm:px-5">
              <div><h2 className="text-sm font-black">Log transaksi</h2><p className="mt-0.5 text-[9px] text-white/35">Riwayat status invoice ini dari sistem pembayaran dan fulfillment.</p></div>
              <span className="inline-flex items-center gap-1.5 rounded-full bg-white/[0.05] px-2 py-1 text-[8px] font-bold text-white/45"><Radio className={`size-3 ${!isFinal(order) ? "animate-pulse text-[#b9ff35]" : "text-white/35"}`} />{!isFinal(order) ? "Realtime" : "Final"}</span>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full min-w-[540px] text-left text-[10px]">
                <thead className="bg-black/15 text-[8px] uppercase tracking-wider text-white/30"><tr><th className="px-4 py-2.5 font-bold sm:px-5">Waktu</th><th className="px-3 py-2.5 font-bold">Sumber</th><th className="px-3 py-2.5 font-bold">Status</th></tr></thead>
                <tbody className="divide-y divide-white/[0.06]">
                  {order.events.map((event, index) => <tr key={`${event.source}-${event.status}-${event.createdAt}-${index}`} className="text-white/55"><td className="whitespace-nowrap px-4 py-3 font-mono text-[9px] sm:px-5">{dateLabel(event.createdAt)}</td><td className="px-3 py-3 font-bold text-white/70">{sourceLabels[event.source] || "Sistem"}</td><td className="px-3 py-3"><span className="inline-flex rounded-md bg-white/[0.05] px-2 py-1 font-semibold text-white/65">{eventLabels[event.status.toLowerCase()] || event.status.replaceAll("_", " ")}</span></td></tr>)}
                </tbody>
              </table>
            </div>
            {!isFinal(order) && <p className="border-t border-white/[0.06] px-4 py-2.5 text-[9px] text-white/30 sm:px-5">Log diperbarui otomatis setiap 3 detik. Tidak perlu refresh halaman.</p>}
          </section>
        </>}

        <section className="panel mt-6 overflow-hidden">
          <div className="flex items-center justify-between gap-3 border-b border-white/[0.08] px-4 py-3 sm:px-5">
            <div>
              <div className="flex items-center gap-2"><History className="size-4 text-[#b9ff35]" /><h2 className="text-sm font-black">Transaksi Terbaru</h2></div>
              <p className="mt-0.5 text-[9px] text-white/35">Aktivitas top up LFAMILIA terbaru. Nomor invoice tidak ditampilkan.</p>
            </div>
            <span className="inline-flex items-center gap-1.5 rounded-full bg-[#b9ff35]/[0.08] px-2 py-1 text-[8px] font-bold text-[#cfff72]"><Radio className="size-3 animate-pulse" /> Live</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-[10px]">
              <thead className="bg-black/15 text-[8px] uppercase tracking-wider text-white/30">
                <tr><th className="px-4 py-2.5 font-bold sm:px-5">Waktu</th><th className="px-3 py-2.5 font-bold">Privasi</th><th className="px-3 py-2.5 font-bold">Produk</th><th className="px-3 py-2.5 font-bold">Nominal</th><th className="px-3 py-2.5 font-bold">Status</th></tr>
              </thead>
              <tbody className="divide-y divide-white/[0.06]">
                {transactions.map((item, index) => <tr key={`${item.maskedReferenceId}-${item.createdAt}-${index}`} className="text-white/55">
                  <td className="whitespace-nowrap px-4 py-3 font-mono text-[9px] sm:px-5">{dateLabel(item.createdAt)}</td>
                  <td className="px-3 py-3 font-mono font-bold text-white/65">{item.maskedReferenceId}</td>
                  <td className="px-3 py-3"><span className="font-bold text-white/70">{item.productName}</span><span className="ml-1 text-white/35">• {item.packageLabel}</span></td>
                  <td className="whitespace-nowrap px-3 py-3 font-bold text-white/70">{formatRupiah(item.total)}</td>
                  <td className="px-3 py-3"><span className="inline-flex rounded-md bg-white/[0.05] px-2 py-1 font-semibold text-white/65">{publicStatusLabels[item.status] || item.status}</span></td>
                </tr>)}
                {!transactions.length && <tr><td colSpan={5} className="px-4 py-8 text-center text-[10px] text-white/30">Belum ada transaksi yang dapat ditampilkan.</td></tr>}
              </tbody>
            </table>
          </div>
          <p className="border-t border-white/[0.06] px-4 py-2.5 text-[9px] text-white/28 sm:px-5">Tidak menampilkan invoice, nama, email, nomor WhatsApp, tujuan akun, atau kode voucher pelanggan.</p>
        </section>
      </main>
    </StoreLayout>
  );
}
