// components/turnstile-widget.tsx
"use client";

import { useEffect, useRef, useState } from "react";

declare global {
  interface Window {
    turnstile?: {
      render(container: HTMLElement, options: {
        sitekey: string;
        callback(token: string): void;
        "expired-callback"(): void;
        "error-callback"(): void;
        theme?: "dark" | "light" | "auto";
        size?: "normal" | "compact";
      }): string;
      remove(widgetId: string): void;
    };
  }
}

export function TurnstileWidget({
  onToken,
}: {
  onToken(token: string): void;
}) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [siteKey, setSiteKey] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    void fetch("/api/security/turnstile", { cache: "no-store" })
      .then(async (response) => response.ok ? response.json() : null)
      .then((data: { enabled?: boolean; siteKey?: string | null } | null) => {
        if (!active) return;
        setSiteKey(data?.enabled && data.siteKey ? data.siteKey : null);
      })
      .catch(() => setSiteKey(null));
    return () => { active = false; };
  }, []);

  useEffect(() => {
    if (!siteKey || !containerRef.current) {
      onToken("");
      return;
    }
    let disposed = false;
    let widgetId: string | null = null;

    const render = () => {
      if (disposed || widgetId || !window.turnstile || !containerRef.current) return;
      widgetId = window.turnstile.render(containerRef.current, {
        sitekey: siteKey,
        theme: "dark",
        size: "normal",
        callback: (token) => onToken(token),
        "expired-callback": () => onToken(""),
        "error-callback": () => onToken(""),
      });
    };

    const existing = document.querySelector<HTMLScriptElement>('script[data-lf-turnstile="true"]');
    if (window.turnstile) render();
    else if (existing) existing.addEventListener("load", render, { once: true });
    else {
      const script = document.createElement("script");
      script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";
      script.async = true;
      script.defer = true;
      script.dataset.lfTurnstile = "true";
      script.addEventListener("load", render, { once: true });
      document.head.appendChild(script);
    }

    return () => {
      disposed = true;
      onToken("");
      if (widgetId && window.turnstile) window.turnstile.remove(widgetId);
      if (containerRef.current) containerRef.current.replaceChildren();
    };
  }, [siteKey, onToken]);

  if (!siteKey) return null;
  return <div className="overflow-hidden rounded-xl border border-white/[0.08] bg-black/10 p-2"><div ref={containerRef} /></div>;
}

// rebuild/resources/js/Components/TurnstileWidget.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';

const props = defineProps({
    siteKey: { type: String, default: '' },
    action: { type: String, required: true },
});
const emit = defineEmits(['update:modelValue']);
const container = ref(null);
let widgetId = null;

const render = () => {
    if (!props.siteKey || !container.value || !window.turnstile) return;
    widgetId = window.turnstile.render(container.value, {
        sitekey: props.siteKey,
        action: props.action,
        theme: 'dark',
        callback: (token) => emit('update:modelValue', token),
        'expired-callback': () => emit('update:modelValue', ''),
        'error-callback': () => emit('update:modelValue', ''),
    });
};

onMounted(() => {
    if (!props.siteKey) return;
    const existing = document.querySelector('script[data-lfamilia-turnstile]');
    if (existing) {
        if (window.turnstile) render();
        else existing.addEventListener('load', render, { once: true });
        return;
    }

    const script = document.createElement('script');
    script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
    script.async = true;
    script.defer = true;
    script.dataset.lfamiliaTurnstile = '1';
    script.addEventListener('load', render, { once: true });
    document.head.appendChild(script);
});

onBeforeUnmount(() => {
    if (widgetId !== null && window.turnstile) window.turnstile.remove(widgetId);
});
</script>

<template>
    <div v-if="siteKey" class="space-y-2">
        <div ref="container"></div>
        <p class="text-xs text-slate-400">Verifikasi keamanan Cloudflare.</p>
    </div>
</template>
