// rebuild/resources/js/Pages/Admin/ForgotPassword.vue
<script setup>
import { computed, ref } from 'vue';
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import { Button } from '../../Components/ui/button';
import { Input } from '../../Components/ui/input';
import TurnstileWidget from '../../Components/TurnstileWidget.vue';

const page = usePage();
const security = computed(() => page.props.security || {});
const turnstile = ref(null);
const form = useForm({ email: '', turnstile_token: '' });

const submit = () => {
    if (form.processing) return;
    form.post('/admin/forgot-password', {
        onFinish: () => {
            form.turnstile_token = '';
            turnstile.value?.reset();
        },
    });
};
</script>

<template>
    <Head title="Lupa Kata Sandi Admin" />
    <main class="lf-admin-auth min-h-screen bg-[#07172d] p-4 text-slate-900">
        <div class="mx-auto grid min-h-[calc(100vh-2rem)] max-w-[980px] place-items-center">
            <form class="w-full max-w-[420px] rounded-xl border border-slate-200 bg-white p-6 shadow-lg" @submit.prevent="submit">
                <h1 class="mb-2 text-xl font-bold text-[#0c1c3b]">Pulihkan kata sandi admin</h1>
                <p class="mb-5 text-sm leading-6 text-slate-600">
                    Masukkan email admin yang terdaftar. Jika akun aktif, kami akan mengirim tautan reset yang berlaku selama 30 menit.
                </p>

                <p v-if="page.props.status" role="status" class="mb-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">
                    {{ page.props.status }}
                </p>

                <label class="text-sm font-semibold text-slate-700">
                    Email admin
                    <Input v-model="form.email" name="email" type="email" autocomplete="email" required
                        class="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 text-base focus:border-[#1769e8]" />
                </label>
                <p v-if="form.errors.email" role="alert" class="mt-2 text-sm text-red-600">{{ form.errors.email }}</p>

                <div v-if="security.turnstile_required" class="mt-4">
                    <p class="mb-2 text-xs text-slate-600">Verifikasi keamanan Cloudflare</p>
                    <TurnstileWidget ref="turnstile" :site-key="security.turnstile_site_key"
                        :action="security.turnstile_action" @token="form.turnstile_token = $event" />
                </div>
                <p v-if="form.errors.turnstile_token" role="alert" class="mt-2 text-sm text-red-600">
                    {{ form.errors.turnstile_token }}
                </p>

                <Button type="submit" class="mt-5 h-10 w-full rounded-md bg-[#1769e8] text-base font-semibold text-white"
                    :disabled="form.processing">
                    {{ form.processing ? 'Mengirim…' : 'Kirim tautan pemulihan' }}
                </Button>

                <div class="mt-4 text-center">
                    <Link href="/admin/login" class="text-sm font-medium text-[#1769e8] hover:underline">
                        Kembali ke login admin
                    </Link>
                </div>
            </form>
        </div>
    </main>
</template>

// app/forgot-password/page.tsx
"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { LoaderCircle, Mail, ShieldCheck } from "lucide-react";
import { TurnstileWidget } from "@/components/turnstile-widget";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [token, setToken] = useState("");
  const [resetKey, setResetKey] = useState(0);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent) {
    event.preventDefault();
    setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch("/api/auth/forgot-password", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ email, turnstileToken: token }),
      });
      const payload = await response.json().catch(() => ({})) as { message?: string; error?: string };
      if (!response.ok) throw new Error(payload.error || "Permintaan reset password gagal.");
      setMessage(payload.message || "Jika email terdaftar, link reset password akan dikirim.");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Permintaan reset password gagal.");
      setToken(""); setResetKey((value) => value + 1);
    } finally { setBusy(false); }
  }

  return <main className="grid min-h-dvh place-items-center bg-[#070910] px-4 py-10 text-white">
    <section className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0d1019] p-6 shadow-2xl sm:p-8">
      <div className="grid size-11 place-items-center rounded-xl bg-[#b9ff35]/10 text-[#cfff72]"><Mail className="size-5" /></div>
      <h1 className="mt-4 text-2xl font-black">Lupa password?</h1>
      <p className="mt-2 text-sm leading-6 text-white/45">Masukkan email akun LFAMILIA. Kami akan mengirim link untuk membuat password baru.</p>
      <form onSubmit={submit} className="mt-6 space-y-4">
        <label className="block"><span className="mb-1.5 block text-xs font-semibold text-white/55">Email</span><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12 w-full rounded-xl border border-white/10 bg-[#10131b] px-4 text-base outline-none focus:border-[#b9ff35]/45" placeholder="nama@email.com" /></label>
        <TurnstileWidget key={resetKey} onToken={setToken} />
        {message && <p className="rounded-xl border border-[#b9ff35]/20 bg-[#b9ff35]/5 p-3 text-xs leading-5 text-[#dfff9d]">{message}</p>}
        {error && <p className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-xs leading-5 text-red-200">{error}</p>}
        <button disabled={busy} className="flex h-12 w-full items-center justify-center rounded-xl bg-[#b9ff35] font-black text-[#091006] disabled:opacity-60">{busy && <LoaderCircle className="mr-2 size-4 animate-spin" />}Kirim link reset</button>
      </form>
      <p className="mt-5 flex items-start gap-2 text-[10px] leading-5 text-white/30"><ShieldCheck className="mt-0.5 size-3.5 shrink-0 text-[#b9ff35]" />Demi keamanan, kami tidak akan memberi tahu apakah email terdaftar atau tidak.</p>
      <Link href="/account" className="mt-5 block text-center text-xs font-bold text-[#cfff72] hover:underline">Kembali ke halaman masuk</Link>
    </section>
  </main>;
}
