// app/reset-password/page.tsx
"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { Eye, EyeOff, LoaderCircle, LockKeyhole } from "lucide-react";
import { useSearchParams } from "next/navigation";

export default function ResetPasswordPage() {
  const params = useSearchParams();
  const token = params.get("token") || "";
  const [password, setPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [show, setShow] = useState(false);
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");

  async function submit(event: FormEvent) {
    event.preventDefault(); setError("");
    if (!token) return setError("Link reset password tidak valid.");
    if (password !== confirmation) return setError("Konfirmasi password tidak sama.");
    setBusy(true);
    try {
      const response = await fetch("/api/auth/reset-password", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ token, password }),
      });
      const payload = await response.json().catch(() => ({})) as { error?: string };
      if (!response.ok) throw new Error(payload.error || "Reset password gagal.");
      setDone(true); setPassword(""); setConfirmation("");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Reset password gagal."); }
    finally { setBusy(false); }
  }

  return <main className="grid min-h-dvh place-items-center bg-[#070910] px-4 py-10 text-white">
    <section className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0d1019] p-6 shadow-2xl sm:p-8">
      <div className="grid size-11 place-items-center rounded-xl bg-[#b9ff35]/10 text-[#cfff72]"><LockKeyhole className="size-5" /></div>
      <h1 className="mt-4 text-2xl font-black">Buat password baru</h1>
      <p className="mt-2 text-sm leading-6 text-white/45">Gunakan minimal 8 karakter. Setelah berhasil, semua sesi login lama akan dikeluarkan.</p>
      {done ? <div className="mt-6"><p className="rounded-xl border border-[#b9ff35]/20 bg-[#b9ff35]/5 p-4 text-sm text-[#dfff9d]">Password berhasil diperbarui.</p><Link href="/account" className="mt-4 flex h-12 items-center justify-center rounded-xl bg-[#b9ff35] font-black text-[#091006]">Masuk kembali</Link></div> :
      <form onSubmit={submit} className="mt-6 space-y-4">
        {[["Password baru", password, setPassword], ["Konfirmasi password", confirmation, setConfirmation]].map(([label, value, setter]) => <label key={String(label)} className="block"><span className="mb-1.5 block text-xs font-semibold text-white/55">{String(label)}</span><span className="relative block"><input required minLength={8} maxLength={72} type={show ? "text" : "password"} autoComplete="new-password" value={String(value)} onChange={(e) => (setter as (v:string)=>void)(e.target.value)} className="h-12 w-full rounded-xl border border-white/10 bg-[#10131b] px-4 pr-12 text-base outline-none focus:border-[#b9ff35]/45" /><button type="button" onClick={() => setShow(v => !v)} aria-label={show ? "Sembunyikan password" : "Tampilkan password"} className="absolute inset-y-0 right-0 grid w-12 place-items-center text-white/40">{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></span></label>)}
        {error && <p className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-xs leading-5 text-red-200">{error}</p>}
        <button disabled={busy || !token} className="flex h-12 w-full items-center justify-center rounded-xl bg-[#b9ff35] font-black text-[#091006] disabled:opacity-50">{busy && <LoaderCircle className="mr-2 size-4 animate-spin" />}Simpan password baru</button>
      </form>}
    </section>
  </main>;
}

// rebuild/resources/js/Pages/Admin/ResetPassword.vue
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import { Button } from '../../Components/ui/button';
import { Input } from '../../Components/ui/input';

const props = defineProps({
    email: { type: String, default: '' },
    token: { type: String, required: true },
});

const form = useForm({
    email: props.email,
    token: props.token,
    password: '',
    password_confirmation: '',
});

const submit = () => {
    if (form.processing) return;
    form.post('/admin/reset-password', {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <Head title="Reset Kata Sandi Admin" />
    <main class="lf-admin-auth min-h-screen bg-[#07172d] p-4 text-slate-900">
        <div class="mx-auto grid min-h-[calc(100vh-2rem)] max-w-[980px] place-items-center">
            <form class="w-full max-w-[420px] rounded-xl border border-slate-200 bg-white p-6 shadow-lg" @submit.prevent="submit">
                <h1 class="mb-2 text-xl font-bold text-[#0c1c3b]">Buat kata sandi admin baru</h1>
                <p class="mb-5 text-sm text-slate-600">Gunakan minimal 12 karakter untuk melindungi akun admin.</p>

                <div class="grid gap-4">
                    <label class="text-sm font-semibold text-slate-700">
                        Email admin
                        <Input v-model="form.email" name="email" type="email" autocomplete="username" required
                            class="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 text-base" />
                    </label>
                    <label class="text-sm font-semibold text-slate-700">
                        Kata sandi baru
                        <Input v-model="form.password" name="password" type="password" autocomplete="new-password" required minlength="12"
                            class="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 text-base" />
                    </label>
                    <label class="text-sm font-semibold text-slate-700">
                        Ulangi kata sandi baru
                        <Input v-model="form.password_confirmation" name="password_confirmation" type="password"
                            autocomplete="new-password" required minlength="12"
                            class="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 text-base" />
                    </label>

                    <p v-for="(error, key) in form.errors" :key="key" role="alert" class="text-sm text-red-600">
                        {{ error }}
                    </p>

                    <Button type="submit" class="h-10 w-full rounded-md bg-[#1769e8] text-base font-semibold text-white"
                        :disabled="form.processing">
                        {{ form.processing ? 'Menyimpan…' : 'Simpan kata sandi baru' }}
                    </Button>
                </div>
                <div class="mt-4 flex flex-wrap justify-between gap-3 text-sm">
                    <Link href="/admin/forgot-password" class="font-medium text-[#1769e8] hover:underline">
                        Minta tautan baru
                    </Link>
                    <Link href="/admin/login" class="font-medium text-[#1769e8] hover:underline">
                        Kembali ke login
                    </Link>
                </div>
            </form>
        </div>
    </main>
</template>
